// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameSubscriptionDO = "scs_subscription"

// SubscriptionDO 订阅表
type SubscriptionDO struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`                          // 主键
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
	ReaderID   int64     `gorm:"column:reader_id;not null;comment:读者id" json:"reader_id"`                               // 读者id
	ColumnID   int64     `gorm:"column:column_id;not null;comment:专栏id" json:"column_id"`                               // 专栏id
	OrderID    int64     `gorm:"column:order_id;not null;comment:订单id" json:"order_id"`                                 // 订单id
	Status     int32     `gorm:"column:status;not null;comment:状态 0/1/2" json:"status"`                                 // 状态 0/1/2
}

// TableName SubscriptionDO's table name
func (*SubscriptionDO) TableName() string {
	return TableNameSubscriptionDO
}
