// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameOrderDO = "scs_order"

// OrderDO 订单表
type OrderDO struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`                          // 主键
	CreateTime    time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime    time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
	No            string    `gorm:"column:no;comment:订单唯一编号，整个系统唯一，带有前缀" json:"no"`                                        // 订单唯一编号，整个系统唯一，带有前缀
	ReaderID      int64     `gorm:"column:reader_id;not null;comment:读者id" json:"reader_id"`                               // 读者id
	ColumnID      int64     `gorm:"column:column_id;not null;comment:专栏id" json:"column_id"`                               // 专栏id
	ColumnQuoteID int64     `gorm:"column:column_quote_id;not null;comment:专栏报价id" json:"column_quote_id"`                 // 专栏报价id
	PaymentID     int64     `gorm:"column:payment_id;not null;comment:支付单id" json:"payment_id"`                            // 支付单id
	Price         int64     `gorm:"column:price;not null;comment:价格（单位：分）" json:"price"`                                   // 价格（单位：分）
	Status        int32     `gorm:"column:status;not null;comment:状态 0/1/2/3/4" json:"status"`                             // 状态 0/1/2/3/4
}

// TableName OrderDO's table name
func (*OrderDO) TableName() string {
	return TableNameOrderDO
}
