// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"github.com/eyebluecn/sc-misc/src/model/po"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newOrderDO(db *gorm.DB, opts ...gen.DOOption) orderDO {
	_orderDO := orderDO{}

	_orderDO.orderDODo.UseDB(db, opts...)
	_orderDO.orderDODo.UseModel(&po.OrderPO{})

	tableName := _orderDO.orderDODo.TableName()
	_orderDO.ALL = field.NewAsterisk(tableName)
	_orderDO.ID = field.NewInt64(tableName, "id")
	_orderDO.CreateTime = field.NewTime(tableName, "create_time")
	_orderDO.UpdateTime = field.NewTime(tableName, "update_time")
	_orderDO.No = field.NewString(tableName, "no")
	_orderDO.ReaderID = field.NewInt64(tableName, "reader_id")
	_orderDO.ColumnID = field.NewInt64(tableName, "column_id")
	_orderDO.ColumnQuoteID = field.NewInt64(tableName, "column_quote_id")
	_orderDO.PaymentID = field.NewInt64(tableName, "payment_id")
	_orderDO.Price = field.NewInt64(tableName, "price")
	_orderDO.Status = field.NewInt32(tableName, "status")

	_orderDO.fillFieldMap()

	return _orderDO
}

// orderDO 订单表
type orderDO struct {
	orderDODo orderDODo

	ALL           field.Asterisk
	ID            field.Int64  // 主键
	CreateTime    field.Time   // 创建时间
	UpdateTime    field.Time   // 更新时间
	No            field.String // 订单唯一编号，整个系统唯一，带有前缀
	ReaderID      field.Int64  // 读者id
	ColumnID      field.Int64  // 专栏id
	ColumnQuoteID field.Int64  // 专栏报价id
	PaymentID     field.Int64  // 支付单id
	Price         field.Int64  // 价格（单位：分）
	Status        field.Int32  // 状态 0/1/2/3/4

	fieldMap map[string]field.Expr
}

func (o orderDO) Table(newTableName string) *orderDO {
	o.orderDODo.UseTable(newTableName)
	return o.updateTableName(newTableName)
}

func (o orderDO) As(alias string) *orderDO {
	o.orderDODo.DO = *(o.orderDODo.As(alias).(*gen.DO))
	return o.updateTableName(alias)
}

func (o *orderDO) updateTableName(table string) *orderDO {
	o.ALL = field.NewAsterisk(table)
	o.ID = field.NewInt64(table, "id")
	o.CreateTime = field.NewTime(table, "create_time")
	o.UpdateTime = field.NewTime(table, "update_time")
	o.No = field.NewString(table, "no")
	o.ReaderID = field.NewInt64(table, "reader_id")
	o.ColumnID = field.NewInt64(table, "column_id")
	o.ColumnQuoteID = field.NewInt64(table, "column_quote_id")
	o.PaymentID = field.NewInt64(table, "payment_id")
	o.Price = field.NewInt64(table, "price")
	o.Status = field.NewInt32(table, "status")

	o.fillFieldMap()

	return o
}

func (o *orderDO) WithContext(ctx context.Context) *orderDODo { return o.orderDODo.WithContext(ctx) }

func (o orderDO) TableName() string { return o.orderDODo.TableName() }

func (o orderDO) Alias() string { return o.orderDODo.Alias() }

func (o orderDO) Columns(cols ...field.Expr) gen.Columns { return o.orderDODo.Columns(cols...) }

func (o *orderDO) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := o.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (o *orderDO) fillFieldMap() {
	o.fieldMap = make(map[string]field.Expr, 10)
	o.fieldMap["id"] = o.ID
	o.fieldMap["create_time"] = o.CreateTime
	o.fieldMap["update_time"] = o.UpdateTime
	o.fieldMap["no"] = o.No
	o.fieldMap["reader_id"] = o.ReaderID
	o.fieldMap["column_id"] = o.ColumnID
	o.fieldMap["column_quote_id"] = o.ColumnQuoteID
	o.fieldMap["payment_id"] = o.PaymentID
	o.fieldMap["price"] = o.Price
	o.fieldMap["status"] = o.Status
}

func (o orderDO) clone(db *gorm.DB) orderDO {
	o.orderDODo.ReplaceConnPool(db.Statement.ConnPool)
	return o
}

func (o orderDO) replaceDB(db *gorm.DB) orderDO {
	o.orderDODo.ReplaceDB(db)
	return o
}

type orderDODo struct{ gen.DO }

func (o orderDODo) Debug() *orderDODo {
	return o.withDO(o.DO.Debug())
}

func (o orderDODo) WithContext(ctx context.Context) *orderDODo {
	return o.withDO(o.DO.WithContext(ctx))
}

func (o orderDODo) ReadDB() *orderDODo {
	return o.Clauses(dbresolver.Read)
}

func (o orderDODo) WriteDB() *orderDODo {
	return o.Clauses(dbresolver.Write)
}

func (o orderDODo) Session(config *gorm.Session) *orderDODo {
	return o.withDO(o.DO.Session(config))
}

func (o orderDODo) Clauses(conds ...clause.Expression) *orderDODo {
	return o.withDO(o.DO.Clauses(conds...))
}

func (o orderDODo) Returning(value interface{}, columns ...string) *orderDODo {
	return o.withDO(o.DO.Returning(value, columns...))
}

func (o orderDODo) Not(conds ...gen.Condition) *orderDODo {
	return o.withDO(o.DO.Not(conds...))
}

func (o orderDODo) Or(conds ...gen.Condition) *orderDODo {
	return o.withDO(o.DO.Or(conds...))
}

func (o orderDODo) Select(conds ...field.Expr) *orderDODo {
	return o.withDO(o.DO.Select(conds...))
}

func (o orderDODo) Where(conds ...gen.Condition) *orderDODo {
	return o.withDO(o.DO.Where(conds...))
}

func (o orderDODo) Order(conds ...field.Expr) *orderDODo {
	return o.withDO(o.DO.Order(conds...))
}

func (o orderDODo) Distinct(cols ...field.Expr) *orderDODo {
	return o.withDO(o.DO.Distinct(cols...))
}

func (o orderDODo) Omit(cols ...field.Expr) *orderDODo {
	return o.withDO(o.DO.Omit(cols...))
}

func (o orderDODo) Join(table schema.Tabler, on ...field.Expr) *orderDODo {
	return o.withDO(o.DO.Join(table, on...))
}

func (o orderDODo) LeftJoin(table schema.Tabler, on ...field.Expr) *orderDODo {
	return o.withDO(o.DO.LeftJoin(table, on...))
}

func (o orderDODo) RightJoin(table schema.Tabler, on ...field.Expr) *orderDODo {
	return o.withDO(o.DO.RightJoin(table, on...))
}

func (o orderDODo) Group(cols ...field.Expr) *orderDODo {
	return o.withDO(o.DO.Group(cols...))
}

func (o orderDODo) Having(conds ...gen.Condition) *orderDODo {
	return o.withDO(o.DO.Having(conds...))
}

func (o orderDODo) Limit(limit int) *orderDODo {
	return o.withDO(o.DO.Limit(limit))
}

func (o orderDODo) Offset(offset int) *orderDODo {
	return o.withDO(o.DO.Offset(offset))
}

func (o orderDODo) Scopes(funcs ...func(gen.Dao) gen.Dao) *orderDODo {
	return o.withDO(o.DO.Scopes(funcs...))
}

func (o orderDODo) Unscoped() *orderDODo {
	return o.withDO(o.DO.Unscoped())
}

func (o orderDODo) Create(values ...*po.OrderPO) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Create(values)
}

func (o orderDODo) CreateInBatches(values []*po.OrderPO, batchSize int) error {
	return o.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (o orderDODo) Save(values ...*po.OrderPO) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Save(values)
}

func (o orderDODo) First() (*po.OrderPO, error) {
	if result, err := o.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*po.OrderPO), nil
	}
}

func (o orderDODo) Take() (*po.OrderPO, error) {
	if result, err := o.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*po.OrderPO), nil
	}
}

func (o orderDODo) Last() (*po.OrderPO, error) {
	if result, err := o.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*po.OrderPO), nil
	}
}

func (o orderDODo) Find() ([]*po.OrderPO, error) {
	result, err := o.DO.Find()
	return result.([]*po.OrderPO), err
}

func (o orderDODo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*po.OrderPO, err error) {
	buf := make([]*po.OrderPO, 0, batchSize)
	err = o.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (o orderDODo) FindInBatches(result *[]*po.OrderPO, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return o.DO.FindInBatches(result, batchSize, fc)
}

func (o orderDODo) Attrs(attrs ...field.AssignExpr) *orderDODo {
	return o.withDO(o.DO.Attrs(attrs...))
}

func (o orderDODo) Assign(attrs ...field.AssignExpr) *orderDODo {
	return o.withDO(o.DO.Assign(attrs...))
}

func (o orderDODo) Joins(fields ...field.RelationField) *orderDODo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Joins(_f))
	}
	return &o
}

func (o orderDODo) Preload(fields ...field.RelationField) *orderDODo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Preload(_f))
	}
	return &o
}

func (o orderDODo) FirstOrInit() (*po.OrderPO, error) {
	if result, err := o.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*po.OrderPO), nil
	}
}

func (o orderDODo) FirstOrCreate() (*po.OrderPO, error) {
	if result, err := o.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*po.OrderPO), nil
	}
}

func (o orderDODo) FindByPage(offset int, limit int) (result []*po.OrderPO, count int64, err error) {
	result, err = o.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = o.Offset(-1).Limit(-1).Count()
	return
}

func (o orderDODo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = o.Count()
	if err != nil {
		return
	}

	err = o.Offset(offset).Limit(limit).Scan(result)
	return
}

func (o orderDODo) Scan(result interface{}) (err error) {
	return o.DO.Scan(result)
}

func (o orderDODo) Delete(models ...*po.OrderPO) (result gen.ResultInfo, err error) {
	return o.DO.Delete(models)
}

func (o *orderDODo) withDO(do gen.Dao) *orderDODo {
	o.DO = *do.(*gen.DO)
	return o
}
