// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/eyebluecn/sc-misc/src/model/po"
)

func newSubscriptionPO(db *gorm.DB, opts ...gen.DOOption) subscriptionPO {
	_subscriptionPO := subscriptionPO{}

	_subscriptionPO.subscriptionPODo.UseDB(db, opts...)
	_subscriptionPO.subscriptionPODo.UseModel(&po.SubscriptionPO{})

	tableName := _subscriptionPO.subscriptionPODo.TableName()
	_subscriptionPO.ALL = field.NewAsterisk(tableName)
	_subscriptionPO.ID = field.NewInt64(tableName, "id")
	_subscriptionPO.CreateTime = field.NewTime(tableName, "create_time")
	_subscriptionPO.UpdateTime = field.NewTime(tableName, "update_time")
	_subscriptionPO.ReaderID = field.NewInt64(tableName, "reader_id")
	_subscriptionPO.ColumnID = field.NewInt64(tableName, "column_id")
	_subscriptionPO.OrderID = field.NewInt64(tableName, "order_id")
	_subscriptionPO.Status = field.NewInt32(tableName, "status")

	_subscriptionPO.fillFieldMap()

	return _subscriptionPO
}

// subscriptionPO 订阅表
type subscriptionPO struct {
	subscriptionPODo subscriptionPODo

	ALL        field.Asterisk
	ID         field.Int64 // 主键
	CreateTime field.Time  // 创建时间
	UpdateTime field.Time  // 更新时间
	ReaderID   field.Int64 // 读者id
	ColumnID   field.Int64 // 专栏id
	OrderID    field.Int64 // 订单id
	Status     field.Int32 // 状态 0/1/2

	fieldMap map[string]field.Expr
}

func (s subscriptionPO) Table(newTableName string) *subscriptionPO {
	s.subscriptionPODo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s subscriptionPO) As(alias string) *subscriptionPO {
	s.subscriptionPODo.DO = *(s.subscriptionPODo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *subscriptionPO) updateTableName(table string) *subscriptionPO {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.CreateTime = field.NewTime(table, "create_time")
	s.UpdateTime = field.NewTime(table, "update_time")
	s.ReaderID = field.NewInt64(table, "reader_id")
	s.ColumnID = field.NewInt64(table, "column_id")
	s.OrderID = field.NewInt64(table, "order_id")
	s.Status = field.NewInt32(table, "status")

	s.fillFieldMap()

	return s
}

func (s *subscriptionPO) WithContext(ctx context.Context) *subscriptionPODo {
	return s.subscriptionPODo.WithContext(ctx)
}

func (s subscriptionPO) TableName() string { return s.subscriptionPODo.TableName() }

func (s subscriptionPO) Alias() string { return s.subscriptionPODo.Alias() }

func (s subscriptionPO) Columns(cols ...field.Expr) gen.Columns {
	return s.subscriptionPODo.Columns(cols...)
}

func (s *subscriptionPO) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *subscriptionPO) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 7)
	s.fieldMap["id"] = s.ID
	s.fieldMap["create_time"] = s.CreateTime
	s.fieldMap["update_time"] = s.UpdateTime
	s.fieldMap["reader_id"] = s.ReaderID
	s.fieldMap["column_id"] = s.ColumnID
	s.fieldMap["order_id"] = s.OrderID
	s.fieldMap["status"] = s.Status
}

func (s subscriptionPO) clone(db *gorm.DB) subscriptionPO {
	s.subscriptionPODo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s subscriptionPO) replaceDB(db *gorm.DB) subscriptionPO {
	s.subscriptionPODo.ReplaceDB(db)
	return s
}

type subscriptionPODo struct{ gen.DO }

func (s subscriptionPODo) Debug() *subscriptionPODo {
	return s.withDO(s.DO.Debug())
}

func (s subscriptionPODo) WithContext(ctx context.Context) *subscriptionPODo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s subscriptionPODo) ReadDB() *subscriptionPODo {
	return s.Clauses(dbresolver.Read)
}

func (s subscriptionPODo) WriteDB() *subscriptionPODo {
	return s.Clauses(dbresolver.Write)
}

func (s subscriptionPODo) Session(config *gorm.Session) *subscriptionPODo {
	return s.withDO(s.DO.Session(config))
}

func (s subscriptionPODo) Clauses(conds ...clause.Expression) *subscriptionPODo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s subscriptionPODo) Returning(value interface{}, columns ...string) *subscriptionPODo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s subscriptionPODo) Not(conds ...gen.Condition) *subscriptionPODo {
	return s.withDO(s.DO.Not(conds...))
}

func (s subscriptionPODo) Or(conds ...gen.Condition) *subscriptionPODo {
	return s.withDO(s.DO.Or(conds...))
}

func (s subscriptionPODo) Select(conds ...field.Expr) *subscriptionPODo {
	return s.withDO(s.DO.Select(conds...))
}

func (s subscriptionPODo) Where(conds ...gen.Condition) *subscriptionPODo {
	return s.withDO(s.DO.Where(conds...))
}

func (s subscriptionPODo) Order(conds ...field.Expr) *subscriptionPODo {
	return s.withDO(s.DO.Order(conds...))
}

func (s subscriptionPODo) Distinct(cols ...field.Expr) *subscriptionPODo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s subscriptionPODo) Omit(cols ...field.Expr) *subscriptionPODo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s subscriptionPODo) Join(table schema.Tabler, on ...field.Expr) *subscriptionPODo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s subscriptionPODo) LeftJoin(table schema.Tabler, on ...field.Expr) *subscriptionPODo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s subscriptionPODo) RightJoin(table schema.Tabler, on ...field.Expr) *subscriptionPODo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s subscriptionPODo) Group(cols ...field.Expr) *subscriptionPODo {
	return s.withDO(s.DO.Group(cols...))
}

func (s subscriptionPODo) Having(conds ...gen.Condition) *subscriptionPODo {
	return s.withDO(s.DO.Having(conds...))
}

func (s subscriptionPODo) Limit(limit int) *subscriptionPODo {
	return s.withDO(s.DO.Limit(limit))
}

func (s subscriptionPODo) Offset(offset int) *subscriptionPODo {
	return s.withDO(s.DO.Offset(offset))
}

func (s subscriptionPODo) Scopes(funcs ...func(gen.Dao) gen.Dao) *subscriptionPODo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s subscriptionPODo) Unscoped() *subscriptionPODo {
	return s.withDO(s.DO.Unscoped())
}

func (s subscriptionPODo) Create(values ...*po.SubscriptionPO) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s subscriptionPODo) CreateInBatches(values []*po.SubscriptionPO, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s subscriptionPODo) Save(values ...*po.SubscriptionPO) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s subscriptionPODo) First() (*po.SubscriptionPO, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*po.SubscriptionPO), nil
	}
}

func (s subscriptionPODo) Take() (*po.SubscriptionPO, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*po.SubscriptionPO), nil
	}
}

func (s subscriptionPODo) Last() (*po.SubscriptionPO, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*po.SubscriptionPO), nil
	}
}

func (s subscriptionPODo) Find() ([]*po.SubscriptionPO, error) {
	result, err := s.DO.Find()
	return result.([]*po.SubscriptionPO), err
}

func (s subscriptionPODo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*po.SubscriptionPO, err error) {
	buf := make([]*po.SubscriptionPO, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s subscriptionPODo) FindInBatches(result *[]*po.SubscriptionPO, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s subscriptionPODo) Attrs(attrs ...field.AssignExpr) *subscriptionPODo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s subscriptionPODo) Assign(attrs ...field.AssignExpr) *subscriptionPODo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s subscriptionPODo) Joins(fields ...field.RelationField) *subscriptionPODo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s subscriptionPODo) Preload(fields ...field.RelationField) *subscriptionPODo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s subscriptionPODo) FirstOrInit() (*po.SubscriptionPO, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*po.SubscriptionPO), nil
	}
}

func (s subscriptionPODo) FirstOrCreate() (*po.SubscriptionPO, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*po.SubscriptionPO), nil
	}
}

func (s subscriptionPODo) FindByPage(offset int, limit int) (result []*po.SubscriptionPO, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s subscriptionPODo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s subscriptionPODo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s subscriptionPODo) Delete(models ...*po.SubscriptionPO) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *subscriptionPODo) withDO(do gen.Dao) *subscriptionPODo {
	s.DO = *do.(*gen.DO)
	return s
}
